services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: dnd-api
    volumes:
      - ./api:/app/api
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: dnd-client
    volumes:
      - ./dnd-client/src:/app/src
      - ./dnd-client/public:/app/public
    ports:
      - "3000:3000" 