FROM node as build-setup
WORKDIR /app
ENV PATH ./node_modules/.bin:$PATH
COPY package.json ./
RUN npm install
COPY ./src ./src
COPY ./public ./public
CMD ["npm", "start"]


# FROM nginx
# COPY --from=build-setup /app/build /usr/share/nginx/html
# COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf